# Snake Game Configuration

# Grid dimensions
grid.width=10
grid.height=10

# GUI settings
gui.enabled=true
game.speed=80

#DQN or QL
agent = QL

agent.dqn.replay=16
agent.dqn.batch=8

agent.alpha=0.001
agent.gamma=0.95

#override epsilon from file
agent.epsilon.override=true

agent.epsilon.start=0.0
agent.epsilon.min=0.005
agent.epsilon.decay = 0.9999995