# Snake Game Configuration

# Grid dimensions
grid.width=10
grid.height=10

# GUI settings
gui.enabled=false
game.speed=80

#DQN or QL
agent = 'DQN'

agent.epsilon.start=1.0
agent.epsilon.min=0.005
agent.epsilon.decay = 0.99995