# Snake Game Configuration

# Grid dimensions
grid.width=10
grid.height=10

# GUI settings
gui.enabled=false
game.speed=30

#DQN or QL
agent = QL

agent.dqn.replay=16
agent.dqn.batch=8

agent.alpha=0.001
agent.gamma=0.95

agent.epsilon.start=1.0
agent.epsilon.min=0.005
agent.epsilon.decay = 0.9999995